### ISSUE TITLE
Issue with read_homer_output()

### ISSUE THREAD

**Issue by chinanicole** [slowkow/homerkit#2]
Hi,

I'm having an issue where I get the following error when running read_homer_output():

```
Found 28 motif.tsv[.gz] files in pDecrease_output/homerResults
Reading 28 of them...
Found 28 motif*.info.html files in pDecrease_output/homerResults
Reading 28 of them...
The following named parsers don't match the column names:
# of Target Sequences with Motif(of 60), # of Background Sequences with Motif(of 490)
```

Not sure what's going on - it looks like those column names should be commented out? Thanks!

**Comment by slowkow** [comment]
Thanks for opening this issue and sharing the error 👍 

You are right, those column names are no good. I just changed the code and it seems to work now.

Could I ask you to try reinstalling the latest GitHub version with `devtools::install_github("slowkow/homerkit")` and try again?

Thank you!

**Comment by chinanicole** [comment]
Looks good now! Thanks, and thanks for making this! Super helpful with the bulky HOMER output.
